### ISSUE TITLE
USER STORY: set up dev and initial deploy

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#1]
EPIC: Avenue Louise website dev environment set up

As a **developer**, I want to **be able to setup Django and install required libraries** to enable me **to develop the site effectively and efficiently**

**Acceptance Criteria**

All required django applications to enable successful deploy

**Tasks**

- [ ] - Create Repository
- [ ] - Install Django applications
- [ ] - Create env.py file
- [ ] - Update settings.py
- [ ] - Freeze requirements
- [ ] - Set up and connect db
- [ ] - Set up and connect cloudinary
- [ ] - Set up Heroku app and deploy
