### ISSUE TITLE
USER STORY: My Profile

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#10]
EPIC: Registration and Account Management

As a **site user** I can **access my personalized user profile** so that **I can view my personal order history and order confirmations and my payment information**

**Acceptance Criteria**
When user is logged in they can access their My Profile page to save their details and see purchasing history

**Tasks**

- [x] 1. Create profiles app and add to installed apps
- [x] 2. Create UserProfile model
- [x] 3. Create profiles view, template, urls.py and add url path
- [x] 4. Link orders to user profiles
- [x] 5. Link webhook to profiles
