### ISSUE TITLE
USER STSORY: Product Details

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#11]
EPIC: Viewing and Navigation

As a **site user** I can **view details for a specific product** so that **I can learn more about it**

**Acceptance Criteria**
User can click on a product to find more information about that product

**Tasks**

- [x] 1. Create products_detail.html
- [x] 2. Create products_detail view
- [x] 3. Add products_detail url path
- [x] 4. Add link to product details on the product image urls
