### ISSUE TITLE
USER STORY: Search functionality

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#13]
EPIC: Viewing and Navigation

As a **site user** I can ** use the search form to search for a product** so that **I can quickly find products that I am interested in**

**Acceptance Criteria**
Search form is clearly visible and returns appropriate products based on search term

**Tasks**

- [x] 1. from django.db.models import Q
- [x] 2. update all_products view to enable user to search through name and description
- [x] 3. Create search form on nav bar
