### ISSUE TITLE
USER STORY: Add to shopping bag

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#14]
EPIC: Purchasing and Checkout

As a **site user** I can **add items to my shopping cart** so that **I can checkout and purchase**

**Acceptance Criteria**
A user can add items to their shopping bag

**Tasks**

- [x] 1. Create bag app and add to installed apps in settings.py
- [x] 2. Create view bag view in views.py
- [x] 3. Create bag/templates/bag and bag.html inside
- [x] 4. Create urls.py in bag app and add path
- [x] 5. Create contexts.py and bag_contents function
- [x] 6. Update settings.py
- [x] 7. Add form to add product to shopping bag
- [x] 8. Create add_to_bag view in views.py
- [x] 9. Add add_to_bag view to urls.py
- [x] 10. Render selected products with details in the shopping bag
