### ISSUE TITLE
USER STORY: Edit shopping bag

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#15]
EPIC: Purchasing and Checkout

As a **site user** I can **modify cart quantities and remove items from the shopping cart** so that **I can ensure I purchase the correct items and quantities**

**Acceptance Criteria**
I can update quantities or remove items from the shopping bag

**Tasks**

- [x] 1.	Create remove_from_bag view in views.py
- [x] 2.	Add path to urls.py
- [x] 3.	Add link in bag.html to remove item
- [x] 4.	Create javascript function to remove item from products library
