### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#16]
EPIC: Purchasing and Checkout

As a **site user** I can **complete my order on the checkout page** so that **I can verify the total is correct, enter my details and make payment**

**Acceptance Criteria**
User can successfully purchase items by adding payment details on checkout page and purchase details are recorded

**Tasks**

- [x] 1. Create checkout app
- [x] 2. Create Order and OrderLineItem models
- [x] 3. Create forms.py and add OrderForm
- [x] 4. Register Order form in admin
- [x] 5. Create signals.py and create functions to update Order total if items are updated or removed
- [x] 6. Create checkout view in views.py
- [x] 7. Create urls.py and add checkout path 
- [x] 8. Create template/checkout folders in checkout and checkout.html
