### ISSUE TITLE
USER STORY: Confirmation Email

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#19]
EPIC: Purchasing and Checkout

As a **site user** I can **receive an email confirmation after checking out** so that **I have a record of my purchases**

**Acceptance Criteria**
Customer receives an email providing order details following successful completion of purchase

**Tasks**

- [x] 1. Create email text content
- [x] 2. Create send_confirmation_email function in webhook_handler.py
- [x] 3. Set default email in settings.py
