### ISSUE TITLE
USER STORY: Base Template

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#2]
EPIC: Avenue Louise website dev environment set up

As a **developer**, I want **to setup a base template** to enable me **to maintain structure and styling across all pages of the website**

**Acceptance Criteria**
Reusable files for base template, header and footer created

**Tasks**

- [x] 1. Create base.html in base directory
- [x] 2. Create home app
- [x] 3. Create templates folder in home app
- [x] 4. Create index.html in home/templates folder and populate with html
- [x] 5. Set up views.py and urls.py to render index.html
- [x] 6. Update settings.py
