### ISSUE TITLE
USER STORY: Add products

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#20]
EPIC: Admin and Store Management

As a **store owner** I can **easily add products to my site** so that **customers can purchase them**

**Acceptance Criteria**
Admin has access to form to add products

**Tasks**

- [x] 1. Create form in products app
- [x] 2. Add add_product to views.py
- [x] 3. Add url path
- [x] 4. Create add_products.html template
