### ISSUE TITLE
USER STORY: Edit products

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#21]
EPIC: Admin and Store Management

As a **store owner** I can **edit details for a product** so that **I can ensure the details are accurate**

**Acceptance Criteria**
Store owner has the functionality to update the product name or details

**Tasks**

- [x] 1. Create edit_products.html
- [x] 2. Add edit function in views.py
- [x] 3. Add edit url path
- [x] 4. Add edit buttons if logged in as superuser
