### ISSUE TITLE
Add and view workshops

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#23]
EPIC: WORKSHOPS

As a **site admin** I can **add a workshop** so that **a user can view workshop details**

**Acceptance Criteria**
Workshops are visible on the workshops page and user can click to view more info and can contact the site owner to enquire and book

**Tasks**

- [x] 1. Create workshops app
- [x] 2. Create workshops model
- [x] 3. Create workshops.html and workshops_detail.html templates
- [x] 4. Create url paths and views
- [x] 5. Create workshop contact form 
- [x] 6. Migrate
