### ISSUE TITLE
Updated design wireframes

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#25]
EPIC: DESIGN

As a **developer**, I want to **review page layout design** to **enable me to ensure UX experience is optimal visually and for navigation**

**Acceptance Criteria**
Site looks clean with clear sections to ensure site navigation is easy for the user

**Tasks**

- [x] 1. Research similar websites to review good design and layouts
- [x] 2. Generate wireframes for updated design
- [x] 3. Make necessary changes to templates and/or css as required by new design
