### ISSUE TITLE
USER STORY: Manual testing

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#29]
EPIC: Manual testing

As a **developer** I can **write manual test** so that **I can find and resolve any bugs**

**Acceptance Criteria**
Full tests and results are documented for all website features and functions

**Tasks**

- [ ] 1. Write full list of tests
- [ ] 2. Take steps to complete each test
- [ ] 3. Resolve and document bugs that are found
- [ ] 4. Document any unresolved bugs
