### ISSUE TITLE
USER STORY: set up authentication

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#3]
EPIC: Avenue Louise authentication

As a **developer**, I want **to setup Authentication** to enable **me to create a superuser and users to set up an account**

**Acceptance Criteria**
Superuser is set up to access admin panel 

**Tasks**

- [x] 1. Install allauth package
- [x] 2. Freeze requirements.txt
- [x] 3. Copy allauth account folder to templates folder in root directory to enable custom styling
- [x] 4. update settings.py
- [x] 5. update urls.py to include allauth.urls
- [x] 6. Makemigrations and migrate
- [x] 7. Create superuser
