### ISSUE TITLE
USER STORY: Testimonials

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#30]
EPIC: <epic>

As a **user** I can **see testimonials** so that **I can feel confident about the quality of service provided by the company**

**Acceptance Criteria**
Testimonials are displayed on the site

**Tasks**
- [x] 1. Create testimonials app
- [x] 2. Create Testimonials model
- [x] 3. Create url paths and views
- [x] 4. Migrate
