### ISSUE TITLE
USER STORY: Add Testimonials

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#31]
EPIC: Admin and Store Management

As a **store owner** I can **easily add testimonials to my site** so that **customers can see them**

**Acceptance Criteria**
Admin has access to form to add testimonials

**Tasks**

- [x] 1. Create form in testimonials app
- [x] 2. Add add_testimonial to views.py
- [x] 3. Add url path
- [x] 4. Create add_testimonial.html template
