### ISSUE TITLE
USER STORY: SEO

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#32]
EPIC: MARKETING

As a **developer** I can **research keywords** so that **I can optimise organic traffic to my website**

**Acceptance Criteria**
Short Tail and Long Tail keywords are researched and added to Meta tags and added as appropriate throughout the website

**Tasks**

- [x] 1. Brianstorm and record general relevant topics
- [x] 2. Search google for these topics and note related searches
- [x] 3. Assess keywords stats on wordtracker.com
- [x] 4. Add keywords and update website description in meta tags and review/update where keywords could be added throughout the site
