### ISSUE TITLE
USER STORY: Header

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#4]
EPIC: Avenue Louise navigation

As a **user** I can **clearly see how to navigate the website from the nav bar** so that **I can easily find what I am looking for**

**Acceptance Criteria**
Nav bar is displayed with logo on all pages and the appropriate links are displayed depending on if the user is logged in 

**Tasks**

- [x] 1. Set up "includes" folder in base directory
- [x] 2. Create header.html in includes folder and populate with html
- [x] 3. update settings.py
