### ISSUE TITLE
USER STORY: PRODUCTS DATABASE

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#6]
EPIC: Avenue Louise databases

As a **developer** I can **create and implement a database model** so that the **Site Admin can upload images and details of products**

**Acceptance Criteria**
Model represents the logical structure of the databases, including the relationships to other databases

**Tasks**

- [x] 1. Create products app
- [x] 2. Create products model
- [x] 3. Create fixtures folder in products app and add products and categories json files
- [x] 4. install Pillow image library
- [x] 5. Freeze requirements
- [x] 6. Update settings.py
- [x] 7. Makemigrations and migrate
- [x] 8. Register model in admin.py
