### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#7]
EPIC: Avenue Louise registration

As an **unregistered user**, I want to **be able to easily register on the website** in order **to save my details and keep track of previous orders**

**Acceptance Criteria**
Users are able to register, sign in and logout of their account

**Tasks**

- [x] 1. Update settings.py to connect to allauth pages
- [x] 2. Install crispy form packages
- [x] 3. Update settings.py to add crispyform requirements
- [x] 4. Freeze requirements
- [x] 5. Update the login.html, signup.html and logout.html to incorporate crispy form styling
- [x] 6. Update header.html with allauth page links
