### ISSUE TITLE
USER STORY: Products list

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#8]
EPIC: Viewing and Navigation

As a **site user** I can **view a list of products** so that **I can easily find products that I am interested in purchasing**

**Acceptance Criteria**
User can view all products 

**Tasks**

- [x] 1. Create template folder in products app
- [x] 2. Create products folder in the templates folder
- [x] 3. Create products.html
