### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by Louibens** [Louibens/PP5-Avenue_Louise#9]
EPIC: Registration & Account Management

As a **site user** I can **easily login or logout** so that **I can access my personal account information**

**Acceptance Criteria**
User can log in and out of the site and will see success message to confirm

**Tasks**

- [x] 1. Update settings.py to connect to allauth pages
- [x] 2. Install crispy form packages
- [x] 3. Update settings.py to add crispyform requirements
- [x] 4. Freeze requirements
- [x] 5. Update the login.html, signup.html and logout.html to incorporate crispy form styling
- [x] 6. Update header.html with allauth page links
